import { readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, test } from 'vitest'

import { readInline, readMarkdown, safeHref, type Block, type Inline } from '@/lib/markdown'

/** The app's own source, which one test below reads to assert what is not in it. */
const SOURCE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

/** Every text run in a tree, flattened, which is what a description actually says. */
function textIn(blocks: readonly Block[]): string {
    return blocks.map(blockText).join('\n')
}

function blockText(block: Block): string {
    switch (block.kind) {
        case 'paragraph':
        case 'heading':
            return inlineText(block.children)
        case 'code':
            return block.text
        case 'list':
            return block.items.map(inlineText).join('\n')
        case 'quote':
            return textIn(block.children)
        case 'table':
            return [block.header, ...block.rows].map((row) => row.map(inlineText).join(' | ')).join('\n')
        case 'rule':
            return ''
    }
}

function inlineText(inlines: readonly Inline[]): string {
    return inlines
        .map((inline) => {
            switch (inline.kind) {
                case 'text':
                case 'code':
                    return inline.text
                case 'emphasis':
                case 'strong':
                case 'link':
                    return inlineText(inline.children)
                case 'break':
                    return '\n'
            }
        })
        .join('')
}

/** Every node kind the tree holds, so a test can say what a description could not become. */
function kindsIn(blocks: readonly Block[]): string[] {
    return blocks.flatMap(blockKinds)
}

function blockKinds(block: Block): string[] {
    switch (block.kind) {
        case 'paragraph':
        case 'heading':
            return [block.kind, ...inlineKinds(block.children)]
        case 'list':
            return [block.kind, ...block.items.flatMap(inlineKinds)]
        case 'quote':
            return [block.kind, ...kindsIn(block.children)]
        case 'table':
            return [block.kind, ...[...block.header, ...block.rows.flat()].flatMap(inlineKinds)]
        default:
            return [block.kind]
    }
}

function inlineKinds(inlines: readonly Inline[]): string[] {
    return inlines.flatMap((inline) =>
        inline.kind === 'emphasis' || inline.kind === 'strong' || inline.kind === 'link'
            ? [inline.kind, ...inlineKinds(inline.children)]
            : [inline.kind],
    )
}

/**
 * Every file this app ships, which is neither the generated shadcn primitives nor a spec.
 *
 * `src/components/ui/` is regenerated by `bunx shadcn add` and is never hand-edited, and a
 * `.test.ts` reaches no browser -- this one names the thing it is looking for, which is why it
 * cannot be looking at itself.
 */
function shippedFiles(root: string): string[] {
    return readdirSync(root).flatMap((entry) => {
        const full = path.join(root, entry)
        if (statSync(full).isDirectory()) return entry === 'ui' ? [] : shippedFiles(full)
        if (entry.endsWith('.test.ts') || entry.endsWith('.test.tsx')) return []
        return entry.endsWith('.ts') || entry.endsWith('.tsx') ? [full] : []
    })
}

/** The two ways React is handed an HTML string: a JSX prop, and a member of a props object. */
const INJECTIONS = ['dangerouslySetInnerHTML=', 'dangerouslySetInnerHTML:']

/**
 * DO NOT DELETE THIS BLOCK, AND DO NOT LOOSEN IT.
 *
 * A description is written by whoever applied the document and rendered to whoever opens the
 * pipeline, so it is somebody else's text on this reader's screen -- which is the whole of the
 * cross-site scripting problem in one sentence. The defence is not a filter that strips tags:
 * it is that no HTML string is ever built. `lib/markdown` answers with a tree of text runs and
 * `components/Markdown` walks that tree into React elements, so raw markup can only ever arrive
 * as a text child, and React escapes every one of those.
 *
 * The last test here is the one that keeps it true: `dangerouslySetInnerHTML` anywhere in this
 * app's own source would undo everything above it in one line, whatever the tests about tokens
 * then said.
 */
describe('a description cannot put markup on the screen', () => {
    test('a script tag survives as the characters somebody typed and as no node that could run', () => {
        const blocks = readMarkdown('<script>alert(1)</script>')

        expect(textIn(blocks)).toContain('<script>alert(1)</script>')
        // The whole vocabulary a description can become. None of these renders an element from
        // a string, so there is no path by which a tag becomes a tag.
        expect(new Set(kindsIn(blocks))).toEqual(new Set(['paragraph', 'text']))
    })

    test('an event handler attribute is text, not an attribute', () => {
        const blocks = readMarkdown('<img src=x onerror="alert(1)">')

        expect(textIn(blocks)).toContain('onerror="alert(1)"')
        expect(kindsIn(blocks)).toEqual(['paragraph', 'text'])
    })

    test('markup inside a sentence stays inside the sentence', () => {
        const blocks = readMarkdown('before <script>alert(1)</script> after')

        expect(textIn(blocks)).toBe('before <script>alert(1)</script> after')
        expect(new Set(kindsIn(blocks))).toEqual(new Set(['paragraph', 'text']))
    })

    test('a javascript: link is drawn as its own words and carries no href at all', () => {
        const blocks = readMarkdown('[click me](javascript:alert(1))')

        expect(textIn(blocks)).toBe('click me')
        expect(kindsIn(blocks)).not.toContain('link')
    })

    test('every scheme but http, https and mailto is refused', () => {
        expect(safeHref('https://example.test/x')).toBe('https://example.test/x')
        expect(safeHref('http://example.test')).toBe('http://example.test')
        expect(safeHref('mailto:someone@example.test')).toBe('mailto:someone@example.test')

        expect(safeHref('javascript:alert(1)')).toBeNull()
        expect(safeHref('JavaScript:alert(1)')).toBeNull()
        expect(safeHref('java\nscript:alert(1)')).toBeNull()
        expect(safeHref('  javascript:alert(1)')).toBeNull()
        expect(safeHref('data:text/html;base64,PHNjcmlwdD4=')).toBeNull()
        expect(safeHref('vbscript:msgbox(1)')).toBeNull()
        expect(safeHref('/pipelines/nightly-etl')).toBeNull()
    })

    test('nothing this app ships injects an HTML string', () => {
        const offenders = shippedFiles(SOURCE).filter((file) => {
            const source = readFileSync(file, 'utf8')
            return INJECTIONS.some((injection) => source.includes(injection))
        })
        expect(offenders).toEqual([])
    })
})

describe('the subset a description is read as', () => {
    test('a link that may be followed keeps its href', () => {
        const blocks = readMarkdown('[the docs](https://example.test/docs)')
        expect(blocks).toEqual([
            {
                kind: 'paragraph',
                children: [{ kind: 'link', href: 'https://example.test/docs', children: [{ kind: 'text', text: 'the docs' }] }],
            },
        ])
    })

    test('emphasis, strong and inline code are their own runs', () => {
        const blocks = readMarkdown('A **bold** and _quiet_ and `literal`.')
        expect(kindsIn(blocks)).toEqual(['paragraph', 'text', 'strong', 'text', 'text', 'emphasis', 'text', 'text', 'code', 'text'])
    })

    test('a heading carries the level it was written at', () => {
        expect(readMarkdown('### What this does')).toEqual([
            { kind: 'heading', level: 3, children: [{ kind: 'text', text: 'What this does' }] },
        ])
    })

    test('a fenced block keeps its language and its text unparsed', () => {
        expect(readMarkdown('```yaml\ncode: nightly-etl\n```')).toEqual([
            { kind: 'code', text: 'code: nightly-etl', language: 'yaml' },
        ])
    })

    test('a list is its items, ordered or not', () => {
        expect(readMarkdown('- one\n- two')).toEqual([
            {
                kind: 'list',
                ordered: false,
                items: [[{ kind: 'text', text: 'one' }], [{ kind: 'text', text: 'two' }]],
            },
        ])
        expect(readMarkdown('1. first\n2. second')[0]).toMatchObject({ kind: 'list', ordered: true })
    })

    test('a blockquote holds blocks of its own', () => {
        expect(readMarkdown('> mind this')).toEqual([
            { kind: 'quote', children: [{ kind: 'paragraph', children: [{ kind: 'text', text: 'mind this' }] }] },
        ])
    })

    test('a table is its heading row, its body rows and how each column is set', () => {
        expect(readMarkdown('| step | block |\n| --- | --- |\n| parse | convert.std |')).toEqual([
            {
                kind: 'table',
                align: [null, null],
                header: [[{ kind: 'text', text: 'step' }], [{ kind: 'text', text: 'block' }]],
                rows: [[[{ kind: 'text', text: 'parse' }], [{ kind: 'text', text: 'convert.std' }]]],
            },
        ])
    })

    test('a column says how it is set, and a cell holds runs like any other block', () => {
        const blocks = readMarkdown('| left | middle | right |\n| :--- | :----: | ----: |\n| a | `b` | **c** |')

        expect(blocks[0]).toMatchObject({ kind: 'table', align: ['left', 'center', 'right'] })
        expect(kindsIn(blocks)).toEqual([
            'table',
            'text',
            'text',
            'text',
            'text',
            'code',
            'strong',
            'text',
        ])
    })

    test('a table between two paragraphs leaves both of them alone', () => {
        const blocks = readMarkdown('What it holds.\n\n| a | b |\n| --- | --- |\n| 1 | 2 |\n\nAnd what it does not.')

        expect(blocks.map((block) => block.kind)).toEqual(['paragraph', 'table', 'paragraph'])
        expect(textIn(blocks)).toBe('What it holds.\na | b\n1 | 2\nAnd what it does not.')
    })

    test('a description of nothing is no blocks at all', () => {
        expect(readMarkdown('')).toEqual([])
        expect(readMarkdown('   \n  ')).toEqual([])
    })
})

describe('one line of a description', () => {
    test("reads a docstring's double backticks as code rather than as their own characters", () => {
        expect(readInline('Written when the value is ``null``.')).toEqual([
            { kind: 'text', text: 'Written when the value is ' },
            { kind: 'code', text: 'null' },
            { kind: 'text', text: '.' },
        ])
    })

    test('reads single backticks the same way', () => {
        expect(readInline('The `output_uri` it wrote.')).toEqual([
            { kind: 'text', text: 'The ' },
            { kind: 'code', text: 'output_uri' },
            { kind: 'text', text: ' it wrote.' },
        ])
    })

    test('is the words themselves when it carries no markup', () => {
        expect(readInline('How long one attempt may take.')).toEqual([
            { kind: 'text', text: 'How long one attempt may take.' },
        ])
    })

    test('is nothing at all when there is nothing to say', () => {
        expect(readInline('')).toEqual([])
    })
})
