#!/usr/bin/env python3
"""Check that no word a person reads is written in a component.

WHY THIS EXISTS. ``src/lib/labels.ts`` is the one place every user-visible string lives, under a
code that says what the string is for. That is only true while it stays true: one literal left in
a component is one phrase nobody reviewing the catalogue will ever see, and one phrase a second
language cannot reach. ``oxlint`` cannot help -- to a JS linter every string is the same string --
so this reads the sources as text and refuses the sites where a literal would be read by a person.

WHAT COUNTS, AND WHAT DELIBERATELY DOES NOT. The rule is "a person reads it", not "it is a
string".

Refused:

* Text between JSX tags. ``<Button>Create</Button>`` is a word on a screen.
* A literal given to an attribute a person reads: ``placeholder``, ``title``, ``aria-label``,
  ``alt``, ``label``, ``noun``, ``emptyMessage``, ``hint``, ``term`` and the rest of ATTRIBUTES.
* A literal given to a property a person reads: ``label:``, ``header:``, ``says:``, ``note:``,
  ``description:`` and the rest of PROPERTIES -- the shape a table column, a settings row or a
  palette action is written in.
* A literal handed to a toast.
* A sentence anywhere at all: a literal with at least two words of prose in it that either ends
  in a full stop, a question mark or an exclamation mark, or starts with a capital and is
  alphabetic throughout. That second rule is what reaches the sentences a lib function returns,
  which no site rule can see. Two words of prose is what keeps a jq or SQL snippet a reference
  card shows -- ``.. | .id?`` -- from reading as a question somebody asked.

Allowed, and each for a reason a person could argue with:

* ``data-testid``, ``id``, ``key``, ``className``, ``name``, ``value``, ``kind``, ``group``,
  ``category``, ``screen``, ``code``: an identifier, a selector or a wire value. Nobody reads one.
* The children of a ``<Kbd>``: a key cap names a key on the keyboard, not a word.
* ``keywords`` on a palette action: matched against what somebody types, never drawn. A second
  language would want them, which is a reason to move them later, not a reason to refuse one now.
* A URL, a path, a media type, a CSS class, an icon name, an SVG path: not language.
* Everything under ``src/components/ui``: the shadcn primitives, regenerated by
  ``bunx shadcn add`` and never hand-edited. The same directory oxlint and oxfmt ignore.
* ``src/lib/labels.ts`` itself, which is where the strings are supposed to be.

THE HOLE THIS CHECK HAS. A bare literal returned from a lib function -- ``return 'queued'`` --
is caught only when it is sentence-shaped. A single lower-case word returned from a function
cannot be told apart from a wire value by reading the text, and guessing would make this check
something people argue with rather than something they fix. Review covers that; so does
``scripts/ui_copy.py``, which prints the catalogue rather than the components.

IT ALSO CHECKS THE CATALOGUE. Every code in ``labels.ts`` has to be reachable from somewhere in
the source, or it is a phrase the product no longer says and the reviewer is reading fiction.

Run it alone with ``uv run python scripts/check_ui_labels.py``; ``make static`` and
``make ui-lint`` both call it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Final

REPO_ROOT = Path(__file__).resolve().parent.parent

FRONTEND = REPO_ROOT / "packages" / "dirigent-server" / "frontend"

#: Where the rule applies: the app's own source.
SRC = FRONTEND / "src"

#: The one place a user-visible string may be written.
CATALOGUE = SRC / "lib" / "labels.ts"

SUFFIXES = {".ts", ".tsx"}

#: Directory names never descended into. ``components/ui`` holds the shadcn primitives.
PRUNE: Final = {"node_modules", "dist", "ui", "__pycache__"}

#: JSX attributes whose value is read by a person.
ATTRIBUTES: Final = frozenset(
    {
        "alt",
        "anything",
        "aria-description",
        "aria-label",
        "aria-placeholder",
        "confirm",
        "detail",
        "empty",
        "emptyMessage",
        "heading",
        "hint",
        "label",
        "noun",
        "placeholder",
        "says",
        "summary",
        "term",
        "title",
        "word",
        "words",
    }
)

#: Object properties whose value is read by a person: a column, a settings row, a palette action.
PROPERTIES: Final = frozenset(
    {
        "action",
        "chip",
        "description",
        "detail",
        "empty",
        "emptyMessage",
        "header",
        "headline",
        "heading",
        "hint",
        "label",
        "message",
        "note",
        "noun",
        "placeholder",
        "says",
        "sentence",
        "summary",
        "term",
        "text",
        "tile",
        "title",
        "word",
        "words",
    }
)

#: Calls whose arguments are said out loud.
CALLS: Final = frozenset({"toast", "toast.success", "toast.error", "toast.warning", "toast.info"})

#: A word of prose: letters, and the apostrophes and hyphens that hold one together.
PROSE_WORD: Final = re.compile(r"^[A-Za-z][A-Za-z'’-]*$")

FIX: Final = (
    "every word a person reads lives in src/lib/labels.ts, under a code that says what it is for. "
    "See docs/ui-conventions.md."
)

DEAD_FIX: Final = (
    "no source reads this label. A phrase the product no longer says is a phrase a reviewer "
    "reads and a translator translates for nothing: take it out of the catalogue."
)


def source_files() -> list[Path]:
    """Every checkable source file, in a stable order.

    Returns:
        The .ts/.tsx files to scan, the catalogue and the test files excluded.
    """
    found: list[Path] = []
    for path in SRC.rglob("*"):
        if path.suffix not in SUFFIXES or path == CATALOGUE:
            continue
        if PRUNE & set(path.relative_to(SRC).parts):
            continue
        if ".test." in path.name:
            continue
        found.append(path)
    return sorted(found)


class Scanner:
    """A JSX-aware walk over one file, yielding the literals and the text a person reads.

    It is not a parser: it tracks exactly enough -- comments, strings, template literals, regular
    expressions, and whether a ``<`` opened an element -- to tell a word on a screen from a word
    in the code around it.
    """

    def __init__(self, text: str) -> None:
        """Hold the source and the position the walk has reached."""
        self.text = text
        self.at = 0
        self.hits: list[tuple[int, str, str]] = []
        #: What to go back to when the current JSX expression or element closes, with the brace
        #: depth and the element name to restore with it.
        self.states: list[tuple[str, int, str]] = []
        #: How many ordinary ``{`` are open inside the current expression. A destructured
        #: parameter -- ``{({ isActive }) => ...}`` -- is braces that close nothing in JSX.
        self.depth = 0
        #: The element whose children the walk is reading.
        self.element = ""
        #: The attribute a literal inside a tag would belong to.
        self.attribute = ""

    def enter(self, back: str) -> None:
        """Remember what to return to, and start a fresh brace count.

        Args:
            back: The state the walk resumes in when this one closes.
        """
        self.states.append((back, self.depth, self.element))
        self.depth = 0

    def leave(self) -> str:
        """Return to what was interrupted.

        Returns:
            The state the walk resumes in.
        """
        back, self.depth, self.element = self.states.pop()
        return back

    def line_of(self, at: int) -> int:
        """Say which line an offset falls on.

        Args:
            at: An offset into the source.

        Returns:
            The 1-based line number.
        """
        return self.text.count("\n", 0, at) + 1

    def run(self) -> list[tuple[int, str, str]]:
        """Walk the whole file.

        Returns:
            ``(line number, the site it was written at, its text)`` triples.
        """
        state = "code"
        while self.at < len(self.text):
            if state == "code":
                state = self.step_code()
            elif state == "tag":
                state = self.step_tag()
            else:
                state = self.step_child()
        return self.hits

    # The three states.

    def step_code(self) -> str:
        """Advance through ordinary TypeScript.

        Returns:
            The state to continue in.
        """
        char = self.text[self.at]
        if self.skip_trivia():
            return "code"
        if char in "'\"`":
            start = self.at
            value = self.read_literal()
            self.classify(start, value)
            return "code"
        if char == "/" and self.starts_regex():
            self.read_regex()
            return "code"
        if char == "{":
            self.at += 1
            self.depth += 1
            return "code"
        if char == "}":
            self.at += 1
            if self.depth > 0:
                self.depth -= 1
                return "code"
            return self.leave() if self.states else "code"
        if char == "<" and self.opens_element():
            self.at += 1
            self.attribute = ""
            self.enter("code")
            self.element = self.tag_name()
            return "tag"
        self.at += 1
        return "code"

    def step_tag(self) -> str:
        """Advance through an element's attributes.

        Returns:
            The state to continue in.
        """
        char = self.text[self.at]
        if self.skip_trivia():
            return "tag"
        if char in "'\"`":
            start = self.at
            value = self.read_literal()
            if self.attribute in ATTRIBUTES:
                self.hits.append((self.line_of(start), self.attribute, value))
            self.attribute = ""
            return "tag"
        if char == "{":
            self.at += 1
            self.enter("tag")
            return "code"
        if self.text.startswith("/>", self.at):
            self.at += 2
            return self.leave()
        if char == ">":
            self.at += 1
            return "child"
        found = re.compile(r"[A-Za-z_$][\w$:.-]*").match(self.text, self.at)
        if found is not None:
            self.at = found.end()
            after = re.compile(r"\s*=").match(self.text, self.at)
            self.attribute = found.group(0) if after is not None else ""
            return "tag"
        self.at += 1
        return "tag"

    def step_child(self) -> str:
        """Advance through an element's children, reading the text between the tags.

        Returns:
            The state to continue in.
        """
        start = self.at
        while self.at < len(self.text) and self.text[self.at] not in "<{":
            self.at += 1
        self.say(start, self.text[start : self.at])
        if self.at >= len(self.text):
            return "child"
        if self.text[self.at] == "{":
            self.at += 1
            self.enter("child")
            return "code"
        if self.text.startswith("</", self.at):
            self.at = self.text.find(">", self.at)
            self.at = len(self.text) if self.at < 0 else self.at + 1
            return self.leave()
        self.at += 1
        self.attribute = ""
        self.enter("child")
        self.element = self.tag_name()
        return "tag"

    def tag_name(self) -> str:
        """Read the name of the element the cursor has just opened.

        Returns:
            The element's name, or the empty string for a fragment.
        """
        found = re.compile(r"[A-Za-z_$][\w$.]*").match(self.text, self.at)
        return "" if found is None else found.group(0)

    # What the walk stops on.

    def skip_trivia(self) -> bool:
        """Step over a comment.

        Returns:
            Whether anything was skipped.
        """
        if self.text.startswith("//", self.at):
            found = self.text.find("\n", self.at)
            self.at = len(self.text) if found < 0 else found
            return True
        if self.text.startswith("/*", self.at):
            found = self.text.find("*/", self.at)
            self.at = len(self.text) if found < 0 else found + 2
            return True
        return False

    def read_literal(self) -> str:
        """Read one string or template literal, keeping its text and eliding its holes.

        A template's ``${...}`` is a value the sentence is written around, so it is read as one
        hole rather than followed: what matters is that the words beside it are words.

        Returns:
            The literal's text, with each interpolation written as a hole.
        """
        quote = self.text[self.at]
        self.at += 1
        out: list[str] = []
        while self.at < len(self.text):
            char = self.text[self.at]
            if char == "\\":
                out.append(self.text[self.at : self.at + 2])
                self.at += 2
                continue
            if char == quote:
                self.at += 1
                break
            if quote == "`" and self.text.startswith("${", self.at):
                self.at += 2
                depth = 1
                while self.at < len(self.text) and depth > 0:
                    if self.text[self.at] in "'\"`":
                        self.read_literal()
                        continue
                    if self.text[self.at] == "{":
                        depth += 1
                    elif self.text[self.at] == "}":
                        depth -= 1
                    self.at += 1
                out.append("{}")
                continue
            if char == "\n" and quote != "`":
                break
            out.append(char)
            self.at += 1
        return "".join(out)

    def starts_regex(self) -> bool:
        """Decide whether the ``/`` at the cursor opens a regular expression.

        Returns:
            Whether what follows should be read as a regex rather than as division.
        """
        back = self.at - 1
        while back >= 0 and self.text[back] in " \t\n\r":
            back -= 1
        return back < 0 or self.text[back] in "(,=:[!&|?{};+*%^~<>"

    def read_regex(self) -> None:
        """Step over a regular expression, character class and all."""
        self.at += 1
        in_class = False
        while self.at < len(self.text):
            char = self.text[self.at]
            if char == "\\":
                self.at += 2
                continue
            if char == "[":
                in_class = True
            elif char == "]":
                in_class = False
            elif char == "/" and not in_class:
                self.at += 1
                return
            elif char == "\n":
                return
            self.at += 1

    def opens_element(self) -> bool:
        """Decide whether the ``<`` at the cursor opens JSX rather than compares or parameterises.

        Returns:
            Whether what follows should be read as an element.
        """
        after = self.text[self.at + 1 : self.at + 2]
        if after != ">" and not re.match(r"[A-Za-z_$]", after):
            return False
        back = self.at - 1
        while back >= 0 and self.text[back] in " \t\n\r":
            back -= 1
        if back < 0:
            return True
        # `<T,>` and `<T extends X,>` are a generic arrow's parameters, which a .tsx file has to
        # write with the comma precisely because they would otherwise read as an element.
        named = re.compile(r"[A-Za-z_$][\w$.]*").match(self.text, self.at + 1)
        if named is not None and re.match(r"\s*(?:,|extends\s)", self.text[named.end() : named.end() + 12]):
            return False
        # An arrow returning an element is the one place a `>` comes just before JSX.
        if self.text[back] == ">":
            return back > 0 and self.text[back - 1] == "="
        # A generic argument follows a name, a closing bracket, or another generic: `useState<x>`,
        # `read()<x>`, `Column<Row>[]`. JSX never does.
        return self.text[back] not in "_$)]" and not self.text[back].isalnum()

    def say(self, start: int, run: str) -> None:
        """Record a run of text between tags, if a person would read it.

        Args:
            start: Where the run begins in the source.
            run: The raw text, whitespace and entities included.
        """
        text = re.sub(r"\s+", " ", run).strip()
        if text == "" or not re.search(r"[A-Za-z]", text):
            return
        # A key cap names a key on somebody's keyboard, which is not a word in a language.
        if self.element == "Kbd":
            return
        self.hits.append((self.line_of(start), "between tags", text))

    def classify(self, start: int, value: str) -> None:
        """Decide whether a literal in ordinary code is one a person reads.

        Args:
            start: Where the literal begins in the source.
            value: Its text.
        """
        if not re.search(r"[A-Za-z]", value):
            return
        before = self.text[max(0, start - 120) : start]
        # A property of an object literal, which oxfmt always writes after a brace, a comma or a
        # line break. Anchoring there is what keeps the false branch of a ternary out.
        found = re.search(r"(?:^|[{,(])\s*([A-Za-z_$][\w$]*)\s*:\s*$", before, re.MULTILINE)
        if found is not None and found.group(1) in PROPERTIES:
            self.hits.append((self.line_of(start), found.group(1), value))
            return
        assigned = re.search(r"([A-Za-z_$][\w$]*)\s*(?<![=!<>])=\s*$", before)
        if assigned is not None and assigned.group(1) in PROPERTIES:
            self.hits.append((self.line_of(start), assigned.group(1), value))
            return
        called = re.search(r"([A-Za-z_$][\w$.]*)\s*\(\s*$", before)
        if called is not None and called.group(1) in CALLS:
            self.hits.append((self.line_of(start), called.group(1), value))
            return
        if sentence_shaped(value):
            self.hits.append((self.line_of(start), "a sentence", value))


def sentence_shaped(value: str) -> bool:
    """Decide whether a literal is prose wherever it was written.

    Args:
        value: The literal's text.

    Returns:
        Whether it reads as something said to a person rather than as a value.
    """
    text = value.strip()
    if " " not in text or len(re.findall(r"[A-Za-z]", text)) < 2:
        return False
    words = text.split(" ")
    # Two words of prose, so a jq or SQL snippet a reference card shows -- `.. | .id?` -- is
    # read as the program it is rather than as a question somebody asked.
    if sum(1 for word in words if PROSE_WORD.match(word.strip(".,;:!?()[]{}\"'"))) < 2:
        return False
    if text.endswith((".", "?", "!")) and not text.endswith(".."):
        return True
    return text[:1].isupper() and all(PROSE_WORD.match(word) for word in words)


def entries() -> list[tuple[str, str]]:
    """Read every label the catalogue mints, as ``(code, what it says)``.

    The catalogue is TypeScript and this is Python, so it is read as text: a name at the head of a
    line, nested under the tables above it by indent, with its value taken to the comma that ends
    it. That is only sound because the file is one object literal per area, written by one
    formatter -- which is part of what the shape is for. ``scripts/ui_copy.py`` prints what this
    returns, so the inventory a copy review reads cannot drift from what the product says.

    Returns:
        Every ``(dotted code, value as written)`` pair, in the order the file declares them.
    """
    if not CATALOGUE.is_file():
        return []
    found: list[tuple[str, str]] = []
    stack: list[tuple[int, str]] = []
    holding = False
    lines = CATALOGUE.read_text(encoding="utf-8").splitlines()
    for at, line in enumerate(lines):
        bare = line.strip()
        if re.match(r"^const [a-z_]+ = \{$", bare):
            stack = [(0, re.sub(r"^const ([a-z_]+).*$", r"\1", bare))]
            holding = True
            continue
        if not holding:
            continue
        if bare.startswith("} as const"):
            holding = False
            continue
        indent = len(line) - len(line.lstrip())
        while len(stack) > 1 and stack[-1][0] >= indent:
            stack.pop()
        opened = re.match(r"^([a-z][a-z0-9_]*): \{$", bare)
        if opened is not None:
            stack.append((indent, opened.group(1)))
            continue
        named = re.match(r"^([a-z][a-z0-9_]*): (.+)$", bare)
        if named is None:
            continue
        code = ".".join([*(name for _, name in stack), named.group(1)])
        found.append((code, value_of(named.group(2), lines, at + 1)))
    return found


def value_of(head: str, lines: list[str], next_line: int) -> str:
    """Read what one label says, following it onto the next line where a formatter broke it.

    Args:
        head: What the declaration line holds after the name.
        lines: Every line of the catalogue.
        next_line: Where to carry on from.

    Returns:
        The value as written, as one line.
    """
    text = head
    while not text.rstrip().endswith(",") and next_line < len(lines):
        text = f"{text.rstrip()} {lines[next_line].strip()}"
        next_line += 1
    text = text.rstrip().removesuffix(",").strip()
    plain = re.fullmatch(r"'(.*)'|`(.*)`", text, re.DOTALL)
    if plain is None:
        return text
    return (plain.group(1) if plain.group(1) is not None else plain.group(2)).replace("\\'", "'")


def dead(every: list[str], sources: list[Path]) -> list[str]:
    """Find every code no source reads.

    A code reached through its parent -- ``LABELS.state.run[status]`` -- counts as read, because
    the table is what the lookup is for.

    Args:
        every: The codes the catalogue mints.
        sources: The files that could read one.

    Returns:
        The codes nothing reads, in catalogue order.
    """
    text = "\n".join(path.read_text(encoding="utf-8") for path in sources)
    read = {found.group(1) for found in re.finditer(r"LABELS\.([\w.]+)", text)}
    reached = set()
    for code in every:
        # A table named on its own -- `LABELS.state.run[status]`, `= LABELS.form.format` -- is a
        # lookup, and reaches everything in it. A sibling named in full reaches only itself, or
        # one label read anywhere would vouch for every label beside it.
        reached.update({code} if code in read else set())
        held = code.rpartition(".")[0]
        while held != "":
            if held in read:
                reached.add(code)
                break
            held = held.rpartition(".")[0]
    return [code for code in every if code not in reached]


def main() -> int:
    """Report every word written outside the catalogue, then fail if there were any.

    Returns:
        A process exit code: 0 when clean, 1 when anything was found.
    """
    files = source_files()
    if not files:
        print("no web UI source to check", file=sys.stderr)
        return 0
    total = 0
    for path in files:
        for lineno, site, text in Scanner(path.read_text(encoding="utf-8")).run():
            total += 1
            print(f"{path.relative_to(REPO_ROOT)}:{lineno}: {site}: {text!r} -- {FIX}")
    every = [code for code, _ in entries()]
    for code in dead(every, files):
        total += 1
        print(f"{CATALOGUE.relative_to(REPO_ROOT)}: {code} -- {DEAD_FIX}")
    if total:
        plural = "" if total == 1 else "s"
        print(f"\n{total} label violation{plural} in {len(files)} files.", file=sys.stderr)
        return 1
    print(f"ui labels ok ({len(every)} labels, {len(files)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
