#!/usr/bin/env python3
"""Check the web UI's Tailwind classes against the type scale in docs/ui-conventions.md.

WHY THIS EXISTS AND WHY IT IS NOT A LINTER RULE. ``oxlint`` lints the TypeScript: hooks, unused
code, correctness. It cannot help here -- to a JS linter a ``className`` is an opaque string
literal, so ``text-[11px]`` and ``text-lg`` are both invisible to it. That blind spot is how a
type scale becomes a suggestion.

ONE RULE, MECHANICAL, AND NO ALLOWLIST. The scale is exactly three sizes, so a class naming a
fourth is a violation whether it was written as an arbitrary value or as one of Tailwind's own
larger steps. A check with exemptions is a check people argue with; this one has nothing to argue
about, which is why it can be an error rather than a warning. Everything else in
docs/ui-conventions.md -- whether a sentence got the prose size, whether a status token was used
as text -- is review's job, not this file's.

THREE NAMED SIZES SIT OUTSIDE THE SCALE, AND THEY ARE NAMED HERE. A stat tile's number is
display type, so it is ``text-stat``; the login brand lockup's wordmark is a brand mark rather
than text, so it is ``text-wordmark``; the login screen's own greeting is ``text-display``. All
three are declared once in index.css and knowable by name. That is not an allowlist: nothing else
is exempt, and the second half of this check reads index.css itself and fails if a size utility
appears there that is not the three plus these. A named exception can be counted; a pattern
cannot.

Run it alone with ``uv run python scripts/check_ui_classes.py``; ``make ui-lint`` calls it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

#: Where the conventions apply: the app's own source, and nothing else.
ROOTS = [REPO_ROOT / "packages" / "dirigent-server" / "frontend" / "src"]

SUFFIXES = {".ts", ".tsx"}

#: Directory names never descended into. ``components/ui`` holds the shadcn primitives, which are
#: generated and re-generated by ``bunx shadcn add`` and are never hand-edited -- so a size inside
#: one is not ours to fix, and flagging it would only teach people to ignore this check. It is the
#: same directory oxlint ignores, for the same reason.
PRUNE = {"node_modules", "dist", "ui", "__pycache__"}

#: An absolute font size written by hand: ``text-[11px]``, ``text-[0.8rem]``, ``text-[13px]`` --
#: including inside a variant, e.g. ``[&_[cmdk-group-heading]]:text-[11px]``. Relative units are
#: deliberately NOT matched: ``text-[0.85em]`` is a fixed ratio TO the scale, which composes with
#: it rather than opting out of it.
ARBITRARY_TYPE_SIZE = re.compile(r"text-\[\d*\.?\d+(?:px|rem|pt)\]")

#: Tailwind's own steps above the scale. The three the app has are xs, sm and base; every larger
#: step is a fourth size arriving through the back door, and index.css does not define them.
OFF_SCALE_TYPE_SIZE = re.compile(r"\btext-(?:lg|xl|[2-9]xl)\b")

FIX = (
    "the type scale is three sizes. Use text-xs (chips, badges, counts, metadata), "
    "text-sm (any sentence), or text-base (a page heading). See docs/ui-conventions.md."
)

#: The stylesheet the scale is declared in, which is the only place a size may be minted.
THEME = ROOTS[0] / "index.css"

#: The three sizes, as the theme tokens that declare them.
SCALE = {"xs", "sm", "base"}

#: The display sizes outside the scale: a stat tile's number, the login brand lockup's wordmark,
#: and the login form's greeting. Nothing else on any screen wears any of them.
NAMED = {"stat", "wordmark", "display"}

#: A size token declared under ``@theme``: ``--text-xs: 0.75rem``. The line-height twins
#: (``--text-xs--line-height``) belong to a size rather than declaring one, so they are skipped.
DECLARED_TOKEN = re.compile(r"--text-([a-z0-9-]+)\s*:")

#: A size declared outside the theme, either as plain CSS (``.text-stat {``) or as a Tailwind
#: utility (``@utility text-wordmark {``), which is what a size needs to be to take a variant.
DECLARED_CLASS = re.compile(r"^(?:\.|@utility\s+)text-([a-z0-9-]+)\s*\{", re.MULTILINE)

CSS_FIX = (
    "index.css declares the scale, and it is three sizes plus the named display sizes "
    "text-stat, text-wordmark and text-display. Minting another here is minting a fourth size. "
    "See docs/ui-conventions.md."
)


def source_files() -> list[Path]:
    """Every checkable source file under ROOTS, in a stable order.

    Returns:
        The .ts/.tsx files to scan.
    """
    found: list[Path] = []
    for root in ROOTS:
        if not root.is_dir():
            continue
        for path in root.rglob("*"):
            if path.suffix not in SUFFIXES:
                continue
            if PRUNE & set(path.relative_to(root).parts):
                continue
            found.append(path)
    return sorted(found)


def violations(path: Path) -> list[tuple[int, str]]:
    """Find off-scale type sizes in one file.

    Args:
        path: The source file to scan.

    Returns:
        ``(line number, offending class)`` pairs, in source order.
    """
    hits: list[tuple[int, str]] = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        for pattern in (ARBITRARY_TYPE_SIZE, OFF_SCALE_TYPE_SIZE):
            hits.extend((lineno, found.group(0)) for found in pattern.finditer(line))
    return sorted(hits)


def minted() -> list[tuple[int, str]]:
    """Find every type size index.css declares that the scale does not name.

    Returns:
        ``(line number, offending declaration)`` pairs, in source order.
    """
    if not THEME.is_file():
        return []
    hits: list[tuple[int, str]] = []
    for lineno, line in enumerate(THEME.read_text(encoding="utf-8").splitlines(), start=1):
        for found in DECLARED_TOKEN.finditer(line):
            name = found.group(1)
            if name.endswith("--line-height") or name.removesuffix("--line-height") in SCALE:
                continue
            if name not in SCALE:
                hits.append((lineno, f"--text-{name}"))
        for found in DECLARED_CLASS.finditer(line):
            if found.group(1) not in NAMED:
                hits.append((lineno, f".text-{found.group(1)}"))
    return hits


def main() -> int:
    """Report every violation, then fail if there were any.

    Returns:
        A process exit code: 0 when clean, 1 when anything was found.
    """
    files = source_files()
    if not files:
        print("no web UI source to check", file=sys.stderr)
        return 0
    total = 0
    for path in files:
        for lineno, found in violations(path):
            total += 1
            print(f"{path.relative_to(REPO_ROOT)}:{lineno}: {found} -- {FIX}")
    for lineno, found in minted():
        total += 1
        print(f"{THEME.relative_to(REPO_ROOT)}:{lineno}: {found} -- {CSS_FIX}")
    if total:
        plural = "" if total == 1 else "s"
        print(f"\n{total} off-scale type size{plural} in {len(files)} files.", file=sys.stderr)
        return 1
    print(f"ui classes ok ({len(files)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
