"""Write an inventory of every pydantic model in the workspace, for reviewing field names."""

import importlib
import inspect
import pkgutil
from pathlib import Path
from types import ModuleType

from pydantic import BaseModel

#: Workspace packages to walk, in dependency order.
PACKAGES = (
    "dirigent_plugin",
    "dirigent_core",
    "dirigent_client",
    "dirigent_server",
    "dirigent_cli",
    "dirigent_blocks",
    "dirigent_storage_s3",
    "dirigent_parquet",
)

#: Where the inventory is written. The directory is ignored; this is a review artifact.
REPORT_PATH = Path("reports/schema-inventory.md")


def modules_of(package: str) -> list[ModuleType]:
    """Import a package and every module under it, skipping any that will not import."""
    try:
        root = importlib.import_module(package)
    except ImportError:
        return []
    found = [root]
    for entry in pkgutil.walk_packages(root.__path__, f"{package}."):
        try:
            found.append(importlib.import_module(entry.name))
        except ImportError:
            continue
    return found


def models_in(module: ModuleType) -> list[type[BaseModel]]:
    """List the models a module defines itself, ignoring the ones it imports."""
    return sorted(
        (
            member
            for _, member in inspect.getmembers(module, inspect.isclass)
            if issubclass(member, BaseModel) and member is not BaseModel and member.__module__ == module.__name__
        ),
        key=lambda model: model.__name__,
    )


def annotation_of(field: object) -> str:
    """Render a field's type the way a reader would write it."""
    annotation = getattr(field, "annotation", None)
    return getattr(annotation, "__name__", str(annotation)).replace("typing.", "")


def render() -> tuple[str, int, int]:
    """Build the report, and count the models and the distinct field names in it."""
    lines = ["# Schema inventory", "", "Generated by `make schemas`. Every pydantic model in the workspace."]
    models = 0
    names: set[str] = set()
    for package in PACKAGES:
        for module in modules_of(package):
            defined = models_in(module)
            if not defined:
                continue
            lines.append(f"\n## {module.__name__}\n")
            for model in defined:
                models += 1
                lines.append(f"### {model.__name__}\n")
                for name, field in model.model_fields.items():
                    names.add(name)
                    lines.append(f"- `{name}`: {annotation_of(field)}")
                lines.append("")
    return "\n".join(lines), models, len(names)


def main() -> None:
    """Write the inventory and say how much it covers."""
    report, models, names = render()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report)
    print(f"{REPORT_PATH}: {models} models, {names} distinct field names")


if __name__ == "__main__":
    main()
